### ISSUE TITLE
UICollectionViewController implementation

### ISSUE THREAD

**Issue by jespr** [infinitered/ProMotion#222]
I'm porting some other code over to ProMotion, and I'm using a UICollectionViewController to display a grid of images. I was thinking about implementing something like PM::CollectionScreen in ProMotion, but want to make sure if that's something you're interested in?

If yes, I will start sketching out a solution in here and get it implemented once it looks ok to you :)

**Comment by ryanlntn** [comment]
This is being addressed by #717

**Comment by jamonholmgren** [comment]
Will close when we merge.

**Comment by jcarbo** [comment]
@jamonholmgren - Looks like this was merged in (https://github.com/infinitered/ProMotion/pull/717) and can be closed.

**Comment by squidpunch** [comment]
thanks @jcarbo!
