### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by j-mcnally** [infinitered/ProMotion#462]
We should come up with a plan for supporting 3.0's android support. Interested in opinions but if we are going to have an iOS DSL we should make it also compatible with android.

http://blog.rubymotion.com/post/87048665656/rubymotion-3-0-sneak-peek-android-support

**Comment by nickyhajal** [comment]
Hey all - not sure if this is the best place to ask but I just thought I'd check in here for an update on Android support for Promotion. Thanks!

**Comment by jamonholmgren** [comment]
@nickyhajal Still in the plans, but got derailed for a while since we haven't had any Android projects at @clearsightstudio for a while. :) I think a reasonable timeframe to expect it would be late spring/early summer.

**Comment by andrewhavens** [comment]
Going to close this old issue. Android support has been implemented in [BluePotion](https://github.com/infinitered/bluepotion), though it is still alpha quality.
