### ISSUE TITLE
uninitialized constant ProMotion::TableViewCell::TableViewCellModule (NameError)

### ISSUE THREAD

**Issue by chrise86** [infinitered/ProMotion#529]
Getting issue related to https://github.com/rubymotion/BubbleWrap/issues/337

    # Gemfile (with RubyMotion 2.31)
    gem "ProMotion", "~> 2.0.0"
    gem "bubble-wrap", "~> 1.7.0"

    # Rakefile
    require 'bubble-wrap/core'

Gives `uninitialized constant BubbleWrap::Constants (NameError)`

Adding `app.detect_dependencies = false` to Rakefile causes:

    uninitialized constant ProMotion::TableViewCell::TableViewCellModule (NameError) 

Is there any way of using these together?

**Comment by andrewhavens** [comment]
Hi @chrise86, this issue sounds similar to #515. Are you still having this issue with the latest versions of ProMotion and BubbleWrap?

**Comment by chrise86** [comment]
Hi @andrewhavens as mentioned in the other issue, not touched any of this since so closing :+1:
