### ISSUE TITLE
Turning tab_bar translucency off breaks view size

### ISSUE THREAD

**Issue by chrise86** [infinitered/ProMotion#531]
On iPad, for some reason turning off tab bar translucency creates a grey bar above the tab bar where it appears to be calculating the height - the height of the tab bar.

I'm using `create_split_screen` for each tab, so not sure how I'd recalculate the view dimensions - the grey bar appears across both the master and detail screens.

I'll try and get a dummy app setup soon.

**Comment by andrewhavens** [comment]
Hi @chrise86, were you ever able to get an example app set up? Is this still an issue, or has it been resolved?

**Comment by chrise86** [comment]
Hi @andrewhavens honestly I'm not sure, it was so long ago and I'm no longer with that project - haven't really touched RM since either, so I'll close :+1:
