### ISSUE TITLE
WKWebView Support

### ISSUE THREAD

**Issue by willrax** [infinitered/ProMotion#543]
Any plans to implement support for this? I can also put some time into adding this.

**Comment by kevinvangelder** [comment]
@willrax Any update on this?

**Comment by willrax** [comment]
@kevinvangelder This is almost ready. Im testing out the code and will be looking for feedback on the api soon. I'll create a PR.

**Comment by jamonholmgren** [comment]
@willrax I ironically started working on this today and got a ways into it. I'll push up my code so you can compare. Didn't get to tests yet.

**Comment by jamonholmgren** [comment]
Here you go: https://github.com/clearsightstudio/ProMotion/tree/wk_web_view

Based on your branch, so you might be able to use some things.

**Comment by willrax** [comment]
Awesome. If you're happy with that sort of api to the web view I can write up some tests for it.

**Comment by jamonholmgren** [comment]
I am, for sure -- tests would be awesome!

**Comment by digitalmoksha** [comment]
@jamonholmgren @willrax   Did the WKWebView work get far enough along for real use or merging?  The performance benefits are supposed to be significant...

**Comment by jamonholmgren** [comment]
@digitalmoksha holy necrothreading... :D No idea, tbh. Give that branch a shot?

**Comment by digitalmoksha** [comment]
No problem, I will.  Just wanted to make sure I wasn't duplicating any effort....
