### ISSUE TITLE
Add `hide_initially` option to `searchable`

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ProMotion#617]
Per https://github.com/clearsightstudio/ProMotion/issues/616#issuecomment-71971173.

```ruby
class HelpScreen < PM::TableScreen
  title "Help"
  searchable placeholder: "Search items", hide_initially: true
```

Implementation would involve something like:

```ruby
  def view_will_appear(animated)
    self.tableView.contentOffset = CGPointMake(0.0, self.searchDisplayController.searchBar.frame.size.height)
    super
  end
```

...plus tests, of course. :) Maybe someone else could take it on?

**Comment by ryanlntn** [comment]
I'll take this one. :smiley:

**Comment by jamonholmgren** [comment]
:+1:

**Comment by jcarbo** [comment]
Looks like this was merged in https://github.com/infinitered/ProMotion/pull/622 and can be closed :+1:

**Comment by markrickert** [comment]
Thanks for the help @jcarbo. We've been kinda lazy with this during the Clearsight/InfiniteRed merger. We appreciate the help!
