### ISSUE TITLE
Make searchable filter a delegate

### ISSUE THREAD

**Issue by sxross** [infinitered/ProMotion#629]
REQUEST/ENHANCEMENT: It would be useful to, instead of `search_text` have the option of calling a user-defined delegate to search existing data in a completely user defined (aka random) way. This has the benefit of following iOS delegate patterns and also reducing the duplication of data inherent in creating a `search_text` field.

Proposed API:

``` ruby
# User code
class MyScreen < PM::TableScreen
  title "My Table"
  searchable placeholder: "Search my table"

  # etc.

  # The delegate method
  #  search_string  is the string typed into the search box
  #  table_cell is the raw table cell data from the collection 
  def search_match(search_string, table_cell)
    # as an example:
    table_cell.first_name.include?(search_string) ||
      table_cell.last_name.include?(search_string)
  end
end
```

@jamonholmgren, @markrickert, does this seem like a good idea?

**Comment by jamonholmgren** [comment]
I like the idea. Just riffing, what about these options:

```ruby
class MyScreen < PM::TableScreen
  title "My Table"
  searchable placeholder: "Search my table", search_method: ->(search_string, table_cell) { ... }
  # or
  searchable placeholder: "Search my table", search_method: :search_match

  def search_match(s, cell)
    # ...
  end
end
```

**Comment by sxross** [comment]
Both look great and either solves the problem that inspired this issue. Rails, obviously, does this for finders -- allowing a `Proc` or a `Symbol`. A `Proc` is a great way to provide readability inline for straightforward cases and a `Symbol` provides more opportunities to create code that can be shared and/or refactored.

I did this in MotionModel with custom comparators for finders, accepting both. Seemed to work well -- users just have to bear in mind that it is not a zero-cost operation. Where a compare on `title` is relatively quick, an OR compare on a number of different fields can get a bit expensive. That's why I glue all the fields together and do one match.

I really like these ideas. I'm just doing a brain-dump here...

**Comment by jamonholmgren** [comment]
Awesome. I'm :+1: on this API. If you think of a better name than `search_method`, I'm fine with that. Maybe `custom_search:` or `search_by:` or `when:`...other ideas?

Also, will wait for @markrickert's thoughts too.

**Comment by sxross** [comment]
I have looked at the code an `PM::TableData` is decoupled from `PM::Table`. As a result, getting the searchable params from inside the `TableData` container is not straightforward. Is there a PM-approved way to do this? If so, I think I can get a proposed implementation together.

**Comment by jamonholmgren** [comment]
Maybe pass them through here? https://github.com/clearsightstudio/ProMotion/blob/master/lib/ProMotion/table/table.rb#L151

**Comment by sxross** [comment]
Please look at https://github.com/sxross/ProMotion/commit/e56e80b3a4a09c899ad389ac00d43ee62cc80937. It does implement custom search as a stabby proc or as a class method referenced by a symbol. Some of the stuff I had to do in order to get `params` into `TableData` and making `TableData` aware of the controller it lives in seemed a bit hacky.

Comments?

**Comment by jamonholmgren** [comment]
@sxross I added a bunch of comments in-line. Looking good!

**Comment by andrewhavens** [comment]
Looks like this has already been implemented, so I'm closing this issue.
