### ISSUE TITLE
ProMotion 3.0 Android/iOS API standardization

### ISSUE THREAD

**Issue by silasjmatson** [infinitered/ProMotion#631]
**EDIT: bug moved to issue #635**

> Opening a new screen with an instance that has `nav_bar: true` causes the parent_screen to not be set.
> 
> According to @jamonholmgren, this is because the Screen initializer will create a wrapper navigation controller when `nav_bar: true` is passed in, which is then discarded when pushed on to an existing navigation controller. However, the `screen#parent_screen` is not getting reset when this happens.

...

This is most likely a fairly easy to fix bug, and a regression test also likewise easy to write, but it does expose the issue with the `:nav_bar` argument. It's kinda out of place.

example:

``` ruby
open SomeScreen.new(nav_bar: true), modal: true
```

Both the `:nav_bar` and `:modal` arguments have to do with how the screen is presented, but the `:nav_bar` is passed into the Screen initialization, which, while very helpful for new RubyMotion devs, also leads them astray in other areas.

For example, I worked on a bit of code today from an app where someone had done the following:

``` ruby
open SomeScreen.new(modal: true, nav_bar: true)
```

... which doesn't work, but one can easily see how the developer might assume that it should.

This led me to read the ProMotion [Goal/Philosophy/Roadmap](https://github.com/clearsightstudio/ProMotion/wiki#goalphilosophyroadmap) in the Wiki again.

> Intuitive: The API should make sense, even to developers unfamiliar with ProMotion.

Originally having `:nav_bar` be an argument passed into the initializer made sense, but it's misleading in that devs will assume, _ituitively_, that they can do the same with other arguments related to screen presentation.
# 

If you've read this far, you may be wondering where I'm going with this. That's a very good question. The answer is of course: **ProMotion 3.0 and Android Support**.

The issue I outlined above is solved by Android in the form of Activities, so I wanted to spark a discussion about possibly building Activities/Presenters that handle the screen presentation on both Android and iOS, while keeping with the same goals of a memorable, intuitive, and likable API.

ProMotion 3.0 will most likely have some breaking changes if we try to keep API's identical across both iOS and Android, so what are your thoughts? Post code examples on how you'd like the API to be, as well as any other questions/comments/concerns you have.

/cc @ryanlntn @markrickert @jamonholmgren @kevinvangelder

**Comment by jamonholmgren** [comment]
:100: Really good stuff.

One of the nice things about being able to pass an instance into `open` is preserving state between opens. But often I'm not actually doing that; many of my screens are discarded on `close` and re-created on `open`. And in Android, activities expect a screen class, not an instance.

Another situation where passing in a `nav_bar: true` to the initializer is nice is when you're creating a split view or tab bar.

```ruby
def on_load(app, options)
  open_tab_bar HomeScreen.new(nav_bar: true), AboutScreen.new(nav_bar: true)
end
```

We'll have to think through how this situation should be avoided. Just thinking out loud:

```ruby
def on_load(app, options)
  open_tab_bar nav_bar(HomeScreen), nav_bar(AboutScreen)
end
```

I'll post some more thinking-out-loud sample API code later. I think we could preserve `nav_bar: true` in the initializer in 3.0+, but output a deprecation warning, simply because of the sheer amount of demo code out there that does this and to ease updating existing apps.

**Comment by silasjmatson** [comment]
Good points. I'm going to take my own advice and try to sketch out what I'd like to see as far as a platform agnostic API for screen handling/presentation.

```ruby
class AppDelegate
  def on_load(app, options)
    open_tab_bar presenter(Screen1, { nav_bar: true }), presenter(Screen2, { nav_bar: false })
  end
end

class Screen1
  def on_some_action
    open presenter(Screen3, { modal: true, animated: false }, { user: some_user })
  end
end

# The `#presenter` method could look something like this
def presenter(klass, presentation_options, screen_options)
  if ios?
    # `open_ios` would pretty much be similar to the current `open` method, with 
    # the exception of moving *all* presentation options to be handled in the proper place
    open_ios klass.new(screen_options), presentation_options
  else
    # Not sure how Android works. :shame:
    # initialize activity, do something with it
  end
end
```

Just my thoughts on a direction we could go. I think we want the users of ProMotion to not have to worry about being on iOS or Android when using the ProMotion API.

**Comment by ryanlntn** [comment]
I don't have much to add just wanted to give :+1: :+1: 

I like Jamon's more literal API but maybe we should build it on something more abstract like Silas's. One thing to note, I think the Action Bar is present by default on Android 3.0+ while it's absent by default on iOS so the expected defaults are different per platform.

**Comment by jamonholmgren** [comment]
Moved the bug to #635.

**Comment by jamonholmgren** [comment]
As we work on ProMotion-android (contained in BluePotion, for now), we're realizing that the best API is something like this:

![screen shot 2015-05-24 at 4 35 40 pm](https://cloud.githubusercontent.com/assets/1479215/7790196/421e0c9a-0233-11e5-8377-b5adf0b381ef.png)

I'll plan on supporting this API in ProMotion 3+ (iOS).
