### ISSUE TITLE
`on_return` issue when using `nav_bar: true` in child screen

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ProMotion#635]
(moved from issue #631 by @silasjmatson)

Opening a new screen with an instance that has `nav_bar: true` causes the parent_screen to not be set.

``` ruby

class Screen2 < PM::Screen
end

class Screen1 < PM::Screen
 # This is wrapped in a NavigationController
  def on_some_action
    open_screen Screen2.new(nav_bar: true)
  end

  def on_return
    puts "on_return" # This will not be called
  end
end
```

According to @jamonholmgren, this is because the Screen initializer will create a wrapper navigation controller when `nav_bar: true` is passed in, which is then discarded when pushed on to an existing navigation controller. However, the `screen#parent_screen` is not getting reset when this happens.

**Comment by kevinvangelder** [comment]
@silasjmatson As you can see from the pull request, we weren't able to replicate this issue.

**Comment by jamonholmgren** [comment]
@markrickert Is this related to your issue?
