### ISSUE TITLE
Bacon::Error: nil.kind_of?(UIBarButtonItem) failed

### ISSUE THREAD

**Issue by bolatk** [infinitered/ProMotion#647]
Hi,
I have installed ProMotion 2.2.1. When I run "rake spec" there were some issues in a console. I did not add any code. The new created app works on iOS Simulator though.
My iOS SDK version is 8.2, RubyMotion 3.6
Stacktrace for "rake spec":
HomeScreen
- has a navigationController
- has a right nav bar button [FAILED - nil.kind_of?(UIBarButtonItem) failed]
- opens the help screen when tapping Help [FAILED - #HomeScreen:0x10bd90e40.kind_of?(HelpScreen) failed]

Bacon::Error: nil.kind_of?(UIBarButtonItem) failed
    spec.rb:745:in `satisfy:': HomeScreen - has a right nav bar button
    spec.rb:759:in`method_missing:'
    spec.rb:316:in `block in run_spec_block'
    spec.rb:459:in`execute_block'
    spec.rb:316:in `run_spec_block'
    spec.rb:331:in`run'

Bacon::Error: #HomeScreen:0x10bd90e40.kind_of?(HelpScreen) failed
    spec.rb:745:in `satisfy:': HomeScreen - opens the help screen when tapping Help
    spec.rb:759:in`method_missing:'
    spec.rb:316:in `block in run_spec_block'
    spec.rb:459:in`execute_block'
    spec.rb:316:in `run_spec_block'
    spec.rb:331:in`run'

4 specifications (4 requirements), 2 failures, 0 errors

I tried to deploy the app to my iPad and there were an error:
<Error>: assertion failed: 12B466: libxpc.dylib + 51955 [...]: 0x7d

Are there any solutions how to solve it?

**Comment by jamonholmgren** [comment]
Hi @bolatkazybayev ! Sorry about that, I've known that there's some issues with the template for a while. Haven't had time to fix them yet.

The main issue right now is that `tap(<UIView>)` doesn't appear to work anymore. I think it could be a bug with UIAutomation, but it's hard to tell. You're going to have to find a different way to simulate taps, unfortunately.
