### ISSUE TITLE
nav_bar_button class method issue

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ProMotion#666]
The new `nav_bar_button` class method has a flaw in that it can only be used to set one nav bar button.

```ruby
class MyScreen < PM::Screen
  nav_bar_button :left, title: "Whatever", action: :my_action
  nav_bar_button :right, title: "Whatever2", action: :my_action2
```

In this case, only the second will be applied. We need to allow both, plus `nav_bar_buttons`.

Because of this, I won't advertise this new method in the 2.3 release notes.

**Comment by markrickert** [comment]
6️⃣6️⃣6️⃣
👹

**Comment by jamonholmgren** [comment]
![](http://media0.giphy.com/media/ToMjGpzot8uTh5nUwnu/giphy.gif)
