### ISSUE TITLE
Is there a better way to "swap" controllers in a navigation stack?

### ISSUE THREAD

**Issue by andrewhavens** [infinitered/ProMotion#706]
I had some trouble figuring out how to achieve the navigation behavior that I needed. However, I managed to come up with some code that worked. I'm wondering if ProMotion provides some helper methods for this navigation scenario...

I have three screens: HomeScreen, SignInScreen, and CreateAccountScreen. From the home screen, you can navigate down the stack to either sign in or create account. However, I needed to be able to navigate from the sign in screen to create account screen (in case the user made a mistake). However, I didn't want to keep pushing more screens on the stack. These are essentially sibling screens which should never be a child of the other. I simply wanted to swap the sign in and create account screens so that if I tapped the back button, it would go back to the home screen.

This is the code that I had to use in order to achieve it:

``` ruby
    append(UILabel, :create_account_label).on(:tap) do
      nav = navigationController
      nav.popToRootViewControllerAnimated(false)
      nav.pushViewController(CreateAccountScreen.new, animated: false)
    end
```

I found that after calling `popToRootViewController` the `navigationController` would be nil when trying to call `pushViewController`, so I had to assign it to a variable that I could reference again.

I set animated to false because it animates as if I were starting from the home screen (root), which is expected, but not desired. It would be nice if I could figure out how to use a fade transition from the sign in screen to the create account screen, but that's low on my priorities at the moment.

**Comment by jamonholmgren** [comment]
I'd try doing something with `UINavigationController#setViewControllers:animated:`. I think you'll have better luck there.

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UINavigationController_Class/#//apple_ref/occ/instm/UINavigationController/setViewControllers:animated:

**Comment by jamonholmgren** [comment]
On further thought, I think we should support that method in ProMotion. Something like this:

```ruby
open RegisterScreen, replace: LoginScreen
```

It would be quite straightforward, I think? Want to give it a go @andrewhavens ?

**Comment by jamonholmgren** [comment]
@andrewhavens Just a tiny tiny bump here. No big deal.

**Comment by andrewhavens** [comment]
@jamonholmgren Yeah, I've been meaning to follow up on this one, but I don't remember exactly what I was going to say. I think I found that `replace` screen, was not the most intuitive way of describing this feature. However, I found `setViewControllers:animated:` really helpful. I'm using this method in other parts of my app when I need to go back a few steps before going forward (or remove the steps in between that a user should not return to). Originally, my thought around swapping screens was to remove the last one and replace it with a different one. I guess `replace` works in this case. But I wonder what would happen if the screen that was being replaced is not the last screen. I'm also not sure how to get the current nav stack so that I can copy it over to `setViewControllers:animated:`. I think those are all of my questions at the moment.

**Comment by jamonholmgren** [comment]
> I'm also not sure how to get the current nav stack so that I can copy it over to `setViewControllers:animated:`

You should be able to just use `viewControllers` for that.

Using `setViewControllers:animated:` is definitely fine. I wonder if we should come up with a good ProMotion alias to keep it more ProMotion-y.

```ruby
open_all [ screen_stack[0], screen_stack[1], MyNewScreen ]
```

Expose `screen_stack` as an alias for `viewControllers`? Or `screens`?

**Comment by andrewhavens** [comment]
Closing this because we now have `replace_nav_stack`:
```ruby
replace_nav_stack([PreviousScreen.new, TopScreen.new], animated: false)
```
