### ISSUE TITLE
2.5.0beta 1 : undefined method `set_searchable_param_defaults

### ISSUE THREAD

**Issue by bmichotte** [infinitered/ProMotion#732]
When using 
```ruby
source 'https://rubygems.org'

gem 'rake'
gem 'ProMotion', git: 'git@github.com:clearsightstudio/ProMotion.git'
gem 'redpotion'
```

I got the following

```
Application Specific Information:
*** Terminating app due to uncaught exception 'NameError', reason: 'undefined method `set_searchable_param_defaults' for module `ProMotion::Table::Searchable' (NameError)
'
terminating with uncaught exception of type NameError
abort() called
CoreSimulator 117.15 - Device: iPad 2 - Runtime: iOS 8.4 (12H141) - DeviceType: iPad 2

Application Specific Backtrace 1:
0   CoreFoundation            0x04516746 __exceptionPreprocess + 182
1   libobjc.A.dylib           0x01729a97 objc_exception_throw + 44
2   MyApp                     0x00be2e06 _ZL10__vm_raisev + 422
3   MyApp                     0x00be2f48 rb_vm_raise + 216
4   MyApp                     0x00adf791 rb_exc_raise + 17
5   MyApp                     0x00ad8ed7 rb_name_error + 135
6   MyApp                     0x00adedb7 rb_print_undef + 343
7   MyApp                     0x00bdaaeb _ZL8vm_aliasmmm + 683
8   MyApp                     0x00bdab67 rb_vm_alias + 23
9   MyApp                     0x00bb07f4 rb_mod_alias_method + 52
10  MyApp                     0x00bd67b4 _ZL20dispatch_rimp_callerPFP11objc_objectS0_P13objc_selectorzEmS1_iPKm + 46452
11  MyApp                     0x00bbcf83 rb_vm_dispatch + 7379
12  MyApp                     0x0010c2bd vm_dispatch + 1373
13  MyApp                     0x005c88c9 rb_scope4 + 105
14  MyApp                     0x005c87dd rb_scope3 + 125
15  MyApp                     0x005c86dd rb_scope2 + 125
16  MyApp                     0x005c85da rb_scope1 + 122
17  MyApp                     0x005cb60f MREP_E9356F4D9958475AA9391DE144536853 + 3183
18  MyApp                     0x001165a9 RubyMotionInit + 5225
19  MyApp                     0x00117b9d main + 109
20  libdyld.dylib             0x064afac9 start + 1
```

The problem disappear when using

```ruby
[clip]
gem 'redpotion', git: 'git@github.com:infinitered/redpotion.git'
```

After a quick search, this makes sense with https://github.com/infinitered/redpotion/blob/v1.4.0/lib/project/pro_motion/data_table_searchable.rb#L6 which as been reworked since 1.4.0

I guess RedPotion will have to bump a release when PM 2.5.0 will be available.

cc @twerth

**Comment by markrickert** [comment]
Yup. This is a redpotion specific issue. We need to release a new version with the fixes in master asap now that CDQ has been fixed to lock motion-yaml to 1.4

**Comment by jamonholmgren** [comment]
Okay, I'll leave this open until RedPotion is fixed.

**Comment by ch0ke** [comment]
Any ETA on the fix of this?  Just updated my gems, and it broke an app that I am working on.  

Gems that were updated on my system:
Gems updated: ProMotion actionmailer actionpack actionview activejob activesupport activemodel activerecord afmotion autoprefixer-rails aws-sdk aws-sdk-core aws-sdk-resources bootstrap-sass bson bson_ext cocaine command_runner_ng font-awesome-rails fuzzy_match geocoder httpclient mime-types mime-types-data mongoid motion-cocoapods motion-yaml mysql2 netrc nokogiri paperclip power_assert rack-cache rails railties redis redis-activesupport redis-rack-cache redis-store rspec-core rspec-support rspec-expectations rspec-mocks rspec-rails run_loop shoulda-matchers simple_token_authentication slop sprockets unicorn unicorn-worker-killer

**Comment by ch0ke** [comment]
any ETA on this? Just updated my gems, and it broke an app I am working on.  Just happened to update RedPotion to 1.4.0.

**Comment by Atastor** [comment]
The ProMotion update to 2.5.0 killed my app as well accordingly. Of course I can stick to 2.4.2; nevertheless ...

**Comment by ch0ke** [comment]
That's what I ended up doing is adding the ProMotion gem to my gemfile locked at 2.4.2.  Be nice to get this fix in now that PM 2.5 is available

**Comment by eliduke** [comment]
As per a suggestion from @bmichotte, I just added this to my gemfile:

`gem "redpotion", git: "https://github.com/infinitered/redpotion.git"`

And then bundled and that fixed it for now.

**Comment by squidpunch** [comment]
@bmichotte @Atastor @ch0ke @bmichotte I'm planning on cutting a release today so you can go back to a released gem

**Comment by jamonholmgren** [comment]
Thanks @squidpunch !

**Comment by squidpunch** [comment]
RMQ and redpotion released, let me know if this fixes the issue guys!

**Comment by eliduke** [comment]
That fixed it for me. This might be obvious, but I had to `bundle update redpotion` and then `rake`.

Thanks again for the quick fix, @squidpunch.

**Comment by squidpunch** [comment]
:+1:

**Comment by jamonholmgren** [comment]
:100:
