### ISSUE TITLE
promotion command not found

### ISSUE THREAD

**Issue by gjlloyd** [infinitered/ProMotion#739]
following the getting started guide, i get:

$ gem install ProMotion
Successfully installed ProMotion-2.4.2
Parsing documentation for ProMotion-2.4.2
Done installing documentation for ProMotion after 2 seconds
1 gem installed
$ promotion new foo
-bash: promotion: command not found

tried a bunch of things but no luck, please advise.

**Comment by GantMan** [comment]
try opening a new terminal window.  Some terminals do no rehash right away.

I use ZSH, and I usually have to type `rehash` before freshly installed commands are accessible.

**Comment by squidpunch** [comment]
if your're using `rbenv` you'll definitely want to `rbenv rehash`

**Comment by gjlloyd** [comment]
thanks for the replies but none of this worked. i'm running OS X and have a pretty basic setup.. can  you tell me what in my path should be set for the promotion command line to work?

below is my gem environment, if that helps.

thanks

RubyGems Environment:
  - RUBYGEMS VERSION: 2.2.2
  - RUBY VERSION: 2.1.2 (2014-05-08 patchlevel 95) [x86_64-darwin13.0]
  - INSTALLATION DIRECTORY: /Users/gareth/.gems
  - RUBY EXECUTABLE: /Users/gareth/.rbenv/versions/2.1.2/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/gareth/.gems/bin
  - SPEC CACHE DIRECTORY: /Users/gareth/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-13
  - GEM PATHS:
     - /Users/gareth/.gems
     - /Users/gareth/.gem/ruby/2.1.0
     - /Users/gareth/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/gareth/.rbenv/versions/2.1.2/bin
     - /usr/local/Cellar/rbenv/0.4.0/libexec
     - /Users/gareth/.rbenv/shims
     - /Users/gareth/.rbenv/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/gareth/bin
     - /Users/gareth/Apps/oracle/instantclient_11_2

**Comment by andrewhavens** [comment]
@gjlloyd I see you are using rbenv. Have you run `rbenv rehash`? Also...

    ruby -v
    gem which ProMotion

**Comment by andrewhavens** [comment]
I'm going to close this since it has been open for a long time. Let us know if you need any more help!
