### ISSUE TITLE
searchable in PM::TableScreen stopped worked

### ISSUE THREAD

**Issue by mixflame** [infinitered/ProMotion#744]
No idea why. It worked before.

I tried to dig in but can't find much information about the code or how it works.

Is there anything I can do to debug the UISearchBar in the PM::TableScreen?

Thanks. I can provide any code as needed but this is how I call it...

``` ruby
class ListScreen < PM::TableScreen
  title "something"
  refreshable
  searchable placeholder: "Search"
  stylesheet ListScreenStylesheet
  include API
  include SugarCube::Timer
#...
```

**Comment by jamonholmgren** [comment]
Hey @jsilverMDX  -- did you get this working again? What version of PM and are you using RedPotion? If so, what version of RP? See also https://github.com/infinitered/ProMotion/issues/732

**Comment by jsilverMDX** [comment]
Hey Jamon. Thank you for your response. We *did* get this working again.
The way was through a custom search method. I don't know much more. We are
using Latest PM and RedPotion.
