### ISSUE TITLE
ProMotion & Stripe pod issue

### ISSUE THREAD

**Issue by kapso** [infinitered/ProMotion#746]
I am using an older version of ProMotion `1.2.1` and when I upgrade to Stripe pod `5.1.4` ProMotion starts to error out. 

This does not work (basically it does not like `action`
```ruby
[{ accessoryType: UITableViewCellAccessoryNone, cell_class: PackageEmptyCell, action: :empty_package_tap }]
```

This works
```ruby
[{ accessoryType: UITableViewCellAccessoryNone, cell_class: PackageEmptyCell }]
```

I am trying this with Xcode 7 (iOS 9) and have tried both RM 4.0 & 3.14

If I try to upgrade to ProMotion `2.4.2` then I run into another issue with RedAlert, see here - https://github.com/GantMan/RedAlert/issues/20

This is the error I see --

 `set_attribute:': can't convert Symbol into Integer (TypeError)

**Comment by jcarbo** [comment]
Hey @kapso you mentioned you upgraded to a later version of ProMotion. Is this still an issue for you? Also v2.5.0 was just released so you can try that as well. If it's still an issue, let us know.

Also there are other issues (https://github.com/infinitered/ProMotion/issues/743 and https://github.com/infinitered/ProMotion/issues/515) that still open and are referencing v1.2.x. If those are resolved would you mind closing them out? Thanks :+1:

**Comment by kapso** [comment]
Yea this is resolved.
