### ISSUE TITLE
iOS 9 crash + Old version of ProMotion

### ISSUE THREAD

**Issue by kapso** [infinitered/ProMotion#748]
Some of our users are reporting consistent crashes on iOS 9 (and these crashes are at different screens). Our application heavily uses ProMotion (`PM::Screen` `PM::FormotionScreen` `PM::TableScreen` `PM::GroupedTableScreen`) but we are on a old version - `1.2.1` as you can see below. Do you know if that could be a problem on iOS 9 and perhaps the reason for these intermittent crashes?

```ruby
gem "afmotion", "2.5"
gem "bubble-wrap", "1.9.2", require: false
gem "cocoapods", "0.37.2" # BE CAREFUL CHANGING VERSION
gem "formotion", "1.8"
gem "motion-cocoapods", "1.7.1"
gem "motion-devices", "0.0.2"
gem "motion-dryclean", "0.0.2"
gem "motion-kit", "0.18.0"
gem "motion_model", "0.6.2"
gem "motion-support", "0.2.6", require: false
gem "ProMotion", "1.2.1"
gem "ProMotion-formotion", "0.1.6"
gem "rake", "10.4.2"
gem "RackMotion", "0.3"
gem "RedAlert", "1.3"
gem "ruby_motion_query", "1.6.1"
gem "sugarcube", "3.3.7", require: false
```

**Comment by jamonholmgren** [comment]
I do know that ProMotion, motion-support, and Formotion don't play all that well together. I've done quite a bit of work in the past to bring them in alignment but eventually gave up on motion-support and Formotion. If you have any crash backtraces or something it would certainly help!

**Comment by kapso** [comment]
The interesting thing is is this was all working before iOS 9, no issues at all. Ever since iOS 9, its been crashing.

Here's the crash report we got from one of our users, unfortunately the .dsym file was not saved for the build in the App store thats crashing. So not sure if this crash report will be of much help. https://gist.github.com/kapso/5e38ad73c32ac1b2340d

Thanks.

**Comment by kapso** [comment]
Also the crashes are only happening for some of the iOS 9 users, not all.

**Comment by kapso** [comment]
@jamonholmgren do you think upgrading to the latest ProMotion will fix these issues. Also would Infinite Red be willing to help with a project like this? Please let me know (kapil@doorman.co) if this is something that you guys would be interested in.

**Comment by jamonholmgren** [comment]
@kapso Sure, I'll email you. It does sound like a separate issue. Just for future reference, what version of RubyMotion are you using?

**Comment by kapso** [comment]
@jamonholmgren great.
Also got some traces of the crash and theres a reference to ProMotion.

**Comment by kapso** [comment]
So `1.2.1` does not work on iOS 9 (or does not work on all iOS 9 devices). Upgraded to `2.4.2` and app stopped crashing.

**Comment by jamonholmgren** [comment]
For some reason I thought you'd already tried that. Glad it works now!

**Comment by jcarbo** [comment]
@kaspo was your issue fixed? I'm trying to help figure out which issues can be closed so let me know (and cc jamon) if so :+1:

**Comment by kapso** [comment]
Yea updating to the latest ProMotion version fixed the issue. Thanks for checking.
