### ISSUE TITLE
UIAlert not working with PM::WebScreen

### ISSUE THREAD

**Issue by poc7667** [infinitered/ProMotion#749]
I tried to invoke alert in the webscreen with 2 methods.
Both are failed, But it works when the app is in the background.

I can get the alert notification in the notification center.

## type1

    rmq.app.alert("Alert with Block") {
      puts message
    }

## type 2
    alert = UIAlertView.new 
    alert.message = message
    alert.show

**Comment by jamonholmgren** [comment]
Did you get this figured out @poc7667 ?

**Comment by poc7667** [comment]
Yes, thanks so much.it's my bad, I used `app.deployment_target = "8.2"` on my iPhone 6 (iOS9) although the app can run, but the alert window is not shown. the error was `undefined method `alert' for RubyMotionQuery::App:Class (NoMethodError)` , and we'd better use `RedAlert` to handle the alert event, because UIAlertView is deprecated on iOS8. thank you~

**Comment by jamonholmgren** [comment]
Oh, okay!
