### ISSUE TITLE
open animation

### ISSUE THREAD

**Issue by hugoerg56** [infinitered/ProMotion#751]
I'm trying to use (animated: true) on the open method, but don't see any animation

**Comment by jamonholmgren** [comment]
Could you give me a little more context, @hugoerg56 ? Where are you using `open` -- in your delegate, in another screen with a nav bar, no nav bar?

**Comment by hugoerg56** [comment]
sorry, just a problem with the pods, with rake clean and reinstalling the pods works...

**Comment by jamonholmgren** [comment]
Sweet. :)
