### ISSUE TITLE
[RedPotion] editing_style: :delete, deleting DataTableScreen cells crashes

### ISSUE THREAD

**Issue by dam13n** [infinitered/ProMotion#752]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (9) must be equal to the number of rows contained in that section before the update (9), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'

Issue exists for 2.4.2 and 2.5.0.beta1. Works for a `TableScreen` though.

**Comment by dam13n** [comment]
This skirts the issue.
```
 def on_cell_deleted(cell)
    cell[:arguments][:model_name].destroy
    false
  end
```

**Comment by dam13n** [comment]
From the slack conversation, looks like this issue is resolved by:
https://github.com/infinitered/ProMotion/commit/ca2aec3ede95a6acab119c6dfc3c6f317b9272a8

**Comment by squidpunch** [comment]
:+1:
