### ISSUE TITLE
how to use a PM:TableView on a table view object embed in a PM:Screen?

### ISSUE THREAD

**Issue by hugoerg56** [infinitered/ProMotion#753]
I have a PM::Screen but I include a table view as subview: ex:

    messages_view = rmq.append(UITableView, :messages).get

now, how can set a PM::TableScreen to this "messages_view" ? to load the data and style.

**Comment by jamonholmgren** [comment]
I generally do this:

```ruby
messages_table = add_child_screen(MessagesTableScreen.new)
messages_view = rmq.append!(table.view, :messages)
```

**Comment by hugoerg56** [comment]
Awesome! thanks!

**Comment by jamonholmgren** [comment]
No problem!

**Comment by jamonholmgren** [comment]
Updated example, had a typo.
