### ISSUE TITLE
animation false not working.

### ISSUE THREAD

**Issue by hugoerg56** [infinitered/ProMotion#754]
On the root screen Im trying to:

open PostFullviewScreen.new(nav_bar: true, animated: false, post: data)

but still opening the screen with animation, I try the close with animated false and works fine.
Any idea?

**Comment by jamonholmgren** [comment]
It should be running this line:

https://github.com/infinitered/ProMotion/blob/master/lib/ProMotion/screen/screen_navigation.rb#L75

Can you confirm if this is the case?

**Comment by hugoerg56** [comment]
Ok I test abd at this point animation still: true passing:
open PostFullviewScreen.new(nav_bar: true, animated: false, post: data)

 fix the problem doing:
open PostFullviewScreen.new(nav_bar: true, animated: false, post: data), {:animated => false}

**Comment by markrickert** [comment]
You're correct there. The `open` method call is the one that needs to have the animated parameter, not the screen constructor. 

A more explicit way of writing it would be:

```ruby
screen = PostFullviewScreen.new(nav_bar: true, animated: false, post: data)
open(screen, {:animated => false})
```
