### ISSUE TITLE
passing params to a long_press_action

### ISSUE THREAD

**Issue by hugoerg56** [infinitered/ProMotion#756]
long_press_action: :my_method_name,

How can I pass a arg to that method? Any idea?

**Comment by jamonholmgren** [comment]
@markrickert ^^

**Comment by markrickert** [comment]
The (https://github.com/infinitered/ProMotion/blob/master/docs/Reference/ProMotion%20TableScreen.md#longpressable)[Longpressable documentation] says that you can just use the `:arguments` value to pass it to longpressable, so this should work:

```ruby
  def table_data
    [{
      cells: [{
        title: "Long press cell",
        action: :normal_action,
        long_press_action: :long_press_action,
        arguments: { foo: "Will be sent along with either action as arguments" }
      }]
    }]
  end

  def long_press_action(args)
    puts args
    # { foo:  "Will be sent along with either action as arguments" }
  end

  def normal_action(args)
    puts args
    # { foo:  "Will be sent along with either action as arguments" }
  end
```

**Comment by hugoerg56** [comment]
omg xD so stupid question.... thanks!

**Comment by markrickert** [comment]
No worries man. That's what we're here for :smile:
