### ISSUE TITLE
problem when creating custom TableViewCell

### ISSUE THREAD

**Issue by apinrdw** [infinitered/ProMotion#759]
Hello, i'm still new and starting build a project with RubyMotion create a custom `PM::TableViewCell`, like this:

![Mockups] (http://i.imgur.com/AZZRioy.png)

The problem is a space on the right of cell, i think that's space for accessory. How i can hide or not use it? so can fill the entire space. [here the gist] (https://gist.github.com/apinrdw/cf447c3d481237856a2f)

Anyone can help? Thanks...

**Comment by squidpunch** [comment]
you're probably going to want to apply `post_cell` to the conentView - and set the width of that to either `w: :full` or `w: screen_width`

the problem (I think, as I have run into it many times before) is you are running a 6 simulator which has a width of 375 points, however a table cell will always only be 320 points on initialization and then is resized when its rendered on the screen.

So when you us `from_right` the superview that you are appending to is 320 points wide (but really should be 375).

you can verify this is the problem by simply calling `rmq.all.reapply_styles` form the REPL with it on screen, and it should adjust to fill the area you are having problems with.

hope that helps...

**Comment by apinrdw** [comment]
@squidpunch, great!

Tried your solution with:
```ruby
def post_cell(st)
    if device.portrait?
      st.frame = { w: device.width }
    else
      st.frame = { w: device.height }
    end
  end
```
 and solved the problem.

Thanks, you help me so much...

**Comment by squidpunch** [comment]
glad to help.  Also @apinrdw if you use `screen_width` it will do this logic for you!

**Comment by apinrdw** [comment]
Wow, very nice! :+1:

**Comment by aesmail** [comment]
> a table cell will always only be 320 points on initialization and then is resized when its rendered on the screen.

@squidpunch this makes so much sense now and solves a lot of problems for me working with table cells! Thank you so much.
