### ISSUE TITLE
Display Custom Controller

### ISSUE THREAD

**Issue by hugoerg56** [infinitered/ProMotion#762]
Im trying to show this viewcontroller ( https://github.com/Kickflip/kickflip-ios-sdk/blob/master/Kickflip/Views/KFBroadcastViewController.m ) with promotion, is posible?

**Comment by squidpunch** [comment]
I am assuming you can `open` it like any other controller

`open KFBroadcastViewController`

**Comment by andrewhavens** [comment]
I'm going to close this since it has been open for a long time. Let us know if you need any more help!
