### ISSUE TITLE
auto row_height for table doesn't seem to be working

### ISSUE THREAD

**Issue by andersennl** [infinitered/ProMotion#767]
Hi, I'm trying to make my table's cells' height dynamic. After looking into the docs and PRs, I've tried both:

``` ruby
class DummyTableScreen < PM::TableScreen
  title "Your title here"
  stylesheet DummyTableScreenStylesheet
  row_height :auto, estimated: 44
...
```

and

``` ruby
  def table_data
    [{
      row_height: :auto,
      estimated_row_height: 50.0,
     cells: @texts.map do |text|
       {
        cell_class: FliessCell,
        style: { title: text },
      }
    end
    }]
  end
```

but maybe I'm doing something wrong somewhere else? This is what the simulator looks like:
<img width="383" alt="bildschirmfoto 2015-11-28 um 09 06 20" src="https://cloud.githubusercontent.com/assets/2667916/11450839/52055964-95af-11e5-83ed-c4bfba9c2ee2.png">

Here is my cell's class and stylesheet:

``` ruby
class FliessCell < PM::TableViewCell
  def on_load
    apply_style :fliess_cell

    content = find(self.contentView)
    @title = content.append! UITextView, :fliess_cell_title
  end

  def title=(value)
    @title.text = value
  end
  def title
    @title
  end
end
```

``` ruby
module FliessCellStylesheet
  def fliess_cell_height
    40
  end

  def fliess_cell(st)
    st.frame = {l: 5, t: 100, w: 80, h: fliess_cell_height}
    st.background_color = color.light_gray
  end

  def fliess_cell_title(st)
    st.frame = {l: 10, fr: 0, centered: :vertical, h: 20}
    st.font = font.medium
    st.color = color.black
    st.scroll_enabled = false
  end
end
```

I'm not sure where the problem is so I'm really thankful for any help. Thanks!

**Comment by jamonholmgren** [comment]
@andersennl Hey! So, the docs should be updated to say this, but automatic row height only works with AutoLayout. That means that RMQ's frame-based height mechanism won't work.

There are a few other options, none ideal. The easiest, in my opinion, is to construct the cell, measure its height, and then throw it away.

```
    def tableView(table_view, heightForRowAtIndexPath: index_path)
      cell = tableView(table_view, cellForRowAtIndexPath: index_path)
      cell.frame.size.height
    end
```

Note this can cause some undesirable side-effects if you are relying on the cell's `on_load` (or `on_cell_reused` on the table) for anything else. This is because you're dequeuing a cell, setting it up, measuring its height, and then throwing it away.

**Comment by andersennl** [comment]
Hey @jamonholmgren thanks for your response. May I ask, how exactly would you advise to use the height form inside the `heightForRowAtIndexPath` method? If I understand you correctly, you just grab the height from `heightForRowAtIndexPath` and pass it to another cell? I mean, until now I've used the `table_data` method to build the cells. Would you dynamically grab the cell's height from `heightForRowAtIndexPath` and assign it to the cells being built in `table_data`?
 
My table class basically just fetches some data in the `on_load` method, and then reloads the table in order to display the fetched data.

Thanks a lot!

**Comment by jamonholmgren** [comment]
Hey @andersennl ! You are overriding a UIKit delegate method, `tableView:heightForRowAtIndexPath:`. In regular ProMotion tables we provide this for you and just grab the `height` property of your cell hash, but in my example you're doing it and constructing the cell and measuring it to provide to UIKit the height.

**Comment by jbender** [comment]
@andersennl would recommend that you take a look at [Motion Kit](https://github.com/motion-kit/motion-kit), which currently supports AutoLayout (though there are rumors that it's coming to RMQ eventually). Feel free to check out [my demo project]()https://github.com/jbender/motion-autolayout-cell-demo for an example of AutoLayout for table cells.

**Comment by andersennl** [comment]
Thanks to both of you for your suggestions.
