### ISSUE TITLE
can we have PM::TableScreen with multiple columns, for example showing the details of student in table view ?

### ISSUE THREAD

**Issue by manju-ms** [infinitered/ProMotion#771]

**Comment by manju-ms** [comment]
We can create a 2 columns for a table using custom cell class of pro motion. 

def table_data
    jobs = Job::JOBS
    cells = []
    jobs.each_with_index do |job, index|
      res = {
          title: job,
          action: :edit_task,
          arguments: {record_num: index},
          cell_class: JobCell,
          style: {
             salary: 500
          }
      }
      cells << res
    end
    [{
         title: "Select Occupation Group For Details",
         title_view_height: 50,
         cells: cells 
     }]
  end

so here we are creating a custom cell called JobCell and we can pass the arguments through style attribute as shown in above class. 

This is custom cell class
class JobCell < PM::TableViewCell

  def salary=(salary)
    @sal ||= begin
      label = add UILabel.alloc.initWithFrame([[ 320, 0 ], [ 50, 30 ]])
      label.font = UIFont.fontWithName("Comic Sans", size:26.0)
      label
    end
    @sal.text = "$#{salary}"
    @sal
  end
end

**Comment by jamonholmgren** [comment]
@manju-ms Do you still need help? I'm sorry I missed this.

**Comment by markrickert** [comment]
Multi-column tableviews are called UICollectionViews. Our library `redpotion` can get you started: https://github.com/infinitered/redpotion You should also read apple's documentation on collection views to help you understand the concepts - https://developer.apple.com/library/ios/documentation/UIKit/Reference/UICollectionView_class/
