### ISSUE TITLE
How to add advertisments using mopup ?

### ISSUE THREAD

**Issue by manju-ms** [infinitered/ProMotion#774]

**Comment by markrickert** [comment]
Hey @manju-ms, You're going to have to give us a bit more information. What are you currently doing that's not working?

**Comment by manju-ms** [comment]
Hello @markrickert, Right now we have built a ios application using red potion, we need to include the MoPub for  advertisments display. Can You help us, How to integrate MoPub into red potion.

**Comment by markrickert** [comment]
You haven't given me much to go on... issues on Github are typically used for specific problems you're having with the codebase so I can't give you specific instructions on integrating an existing service into your app.

That being said, it looks like mopub has an SDK - you will likely need to pull that down, vendor it in the project and then wire up the proper hooks based on their guides

1. install the pod - https://github.com/mopub/mopub-ios-sdk/wiki/Getting-Started#using-cocoapods
2. write code to do what you want, following the documentation mopub provides for their iOS SDK
3. :tada:

If you run into _specific implementation issues_ with redpotion & mopub, feel free to open another issue and we'll see what we can do to help, but it should be fairly straightforward if you've already created the app.
