### ISSUE TITLE
Ready to cut a 2.6.1 release?

### ISSUE THREAD

**Issue by andrewhavens** [infinitered/ProMotion#780]
Looks like we have a few bug fixes lined up in master. Can we cut a 2.6.1 release?

https://github.com/infinitered/ProMotion/compare/v2.6.0...master

Let me know if there is a process that I can adhere to in order to make this go smoother.

**Comment by jamonholmgren** [comment]
@andrewhavens LGTM :shipit:

**Comment by andrewhavens** [comment]
Still need to do this 😱

**Comment by jamonholmgren** [comment]
![what year is it](http://i.imgur.com/odzaUO6.gif)

**Comment by andrewhavens** [comment]
Finally got around to doing this! https://github.com/infinitered/ProMotion/releases/tag/v2.6.1
