### ISSUE TITLE
Selection style not working

### ISSUE THREAD

**Issue by afestein** [infinitered/ProMotion#782]
Hey guys,

I'm struggling to get `selection_style` working on a very simple table:

```
class Team < PM::TableScreen
  def table_data
    [{
      cells: [
        { title: "Boston Celtics", selection_style: :blue },
        { title: "Brooklyn Nets", selection_style: :blue }
      ]
    }]
  end
end
```

According to the [docs](http://promotion.readthedocs.io/en/master/Reference/ProMotion%20Table%20-%20Cell%20Options/) I think I'm using it correctly. 

I'm expecting that when tapping a row it will turn blue, in reality it adopts the 'highlighted' style for a moment and then goes back to a white background: 

<img width="377" alt="screen shot 2016-06-04 at 9 36 35 am" src="https://cloud.githubusercontent.com/assets/6790096/15795736/de482448-2a37-11e6-8f53-fab1d78f46b4.png">

I've checked the value of `table_view.allowsSelection` and it's set to `true`. 

Does anybody please have any ideas or suggestions? 

Many thanks.

**Comment by andrewhavens** [comment]
Hi @afestein. Are you trying to make it so that when you tap on a row, it stays selected? I don't think UITableViewCells work that way by default. You can try setting `keep_selection: true`. Alternatively, if you're trying to create a sort of checklist, you might consider changing the accessory view to a checkmark.

**Comment by afestein** [comment]
Thanks for the reply and suggestions. Yes I was trying to get the cell to stay highlighted and a checkmark accessory was the decoration I needed. I tried this a lot of different ways and couldn't seem to get an accessory to show for a selected cell (and I needed to keep track of the selected cell). 

I ended up using a custom cell class extending `PM::TableViewCell` and then a motion-kit layout to build the background I needed using `selectedBackgroundView`.

**Comment by andrewhavens** [comment]
Ah, okay. So you found a solution? Is it okay if we close this issue then?

**Comment by afestein** [comment]
I did find a solution, but I think it's still unexplained why `selection_style: :blue` has no effect in the code I'm using above. I'd expect a blue selection style of some kind to appear, but here's what I get: 

![tphzc4ptd0](https://cloud.githubusercontent.com/assets/6790096/16641918/c6864fb2-4448-11e6-99a3-03b8073dc2fe.gif)

**Comment by andrewhavens** [comment]
The reason is that blue no longer means blue. From the Apple docs:

> In iOS 7, the selection color is no longer blue. Use UITableViewCellSelectionStyleDefault instead.

So I guess it's still around for legacy support. If you'd like, do you mind sending a PR that makes note of that change?
