### ISSUE TITLE
Previous screen title as inactive back button

### ISSUE THREAD

**Issue by wafcio** [infinitered/ProMotion#783]
When in HomeScreen I will write:

```
class HomeScreen < PM::TableScreen
  title "Root Title"

  def on_load
    open(CouponsScreen)
  end
```

and in CouponsScreen I have
```
class CouponsScreen < PM::TableScreen
  title "Coupons"

  def on_load
    self.navigationItem.hidesBackButton = true
  end
```

then I see:
<img width="413" src="https://cloud.githubusercontent.com/assets/945115/16144884/1ce014ca-3476-11e6-929a-7bdebb7793ca.png">

When I turn off hide button on CouponsScreen I see:

<img width="428" src="https://cloud.githubusercontent.com/assets/945115/16144876/0f511fa2-3476-11e6-96ee-95617cd05632.png">

When I try to open CouponsScreen with `open_root_screen` then I even don't see top bar (with title).

**Comment by andrewhavens** [comment]
When you call `open_root_screen` you need to specify `nav_bar: true` or you won't get the nav bar. Does that solve your problem?

**Comment by wafcio** [comment]
This solved my issue, thank you for this. Unfortunatelly it doesn't explain why I saw "Root Title", when I open screen after click on button this text is invisible - maybe it is some other bug, but right now it doesn't matter for me.

**Comment by andrewhavens** [comment]
This looks like normal behavior to me. If you are trying to hide/remove the back button and text, there are different ways to do it, but I think opening a root screen is the best way.
