### ISSUE TITLE
Unable to add remote image to nav_bar button

### ISSUE THREAD

**Issue by augustosamame** [infinitered/ProMotion#789]
Hello. My nav_bar should show the logged_in user's picture on the right and clicking on it should open a Profile screen.

It works fine with a new user that has not uploaded a profile picture yet, and therefore It's using a local placeholder image, but when `Auth.current_user["image"]` contains an URL pointing to the user's profile image, it no longer works.

    def on_load

    image_view = UIImageView.alloc.initWithFrame(CGRectMake(0, 0, 50, 50))
    image_view.contentMode = UIViewContentModeScaleAspectFit
    image_view.setImageWithURL(Auth.current_user["image"])

    set_nav_bar_button :right,
      image: Auth.current_user["image"].nil? ? image.resource("icon_user_50x50.png") : image_view,
      action: :open_profile

    end

But when a remote image exists, this code does not work properly. It shows the image, but nothing happens when it is tapped / clicked.

If I exchange this line: 

    image: Auth.current_user["image"].nil? ? image.resource("icon_user_50x50.png") : image_view,

for this one:

    image: Auth.current_user["image"].nil? ? image.resource("icon_user_50x50.png") : image.from_view(image_view),

tapping / clicking works, but no image is shown.

Any help would be appreciated.

**Comment by andrewhavens** [comment]
Hi @augustosamame,

I can't say that I've ever tried to use a remote image in a nav bar button, but I think it should be possible. I think your problem is that the `image` option expects to receive a `UIImage`, not a `UIImageView`.

Try using the `custom_view` option:

```ruby
image_view = UIImageView.alloc.initWithFrame(CGRectMake(0, 0, 50, 50))
image_view.contentMode = UIViewContentModeScaleAspectFit
image_view.placeholder_image(image.resource("icon_user_50x50.png"))
image_view.remote_image(Auth.current_user["image"])

set_nav_bar_button :right, custom_view: image_view, action: :open_profile
```

**Comment by augustosamame** [comment]
Hi. Ok. I've refactored it a bit using your suggestion and the image now shows! However no matter what I do, it is not clickable. The `:open_profile` action does not fire.

```
image_view = UIImageView.alloc.initWithFrame(CGRectMake(0, 0, 40, 40))
image_view.contentMode = UIViewContentModeScaleAspectFit
placeholder = UIImage.imageNamed "icon_user_50x50.png"
image_view.url = {url: Auth.current_user["image"].nil? ? "https://s3.amazonaws.com/facesmobileappprofiles/default-user-icon-profile.png" : Auth.current_user["image"], placeholder: placeholder}

set_nav_bar_button :right, custom_view: image_view, action: :open_profile
```

**Comment by augustosamame** [comment]
When using a custom_view for a nav_bar button, the button is no longer clickable. To fix this, it is necessary to implement the functionality manually by adding:

image_view.setUserInteractionEnabled(true)
    image_view.addGestureRecognizer(UITapGestureRecognizer.alloc.initWithTarget(self, action: :open_profile))
