### ISSUE TITLE
Switching to Screen if already open

### ISSUE THREAD

**Issue by augustosamame** [infinitered/ProMotion#790]
Sorry about the newbie question

I am using a TabBar to navigate my app and it works great because it switches seamlessly between screens. However, I have not been able to duplicate its behaviour inside the screens themselves.

My chat screen has 2 buttons: one that shows a messaging list and the other a friend list. When clicking the buttons I open the relevant screens. However, it is creating a new screen each time I press a button instead of just switching to the screen that already exists (as in the TabBar). How can I do this?

BTW I am using `open ScreenName`, not `open ScreenName.new`

**Comment by jamonholmgren** [comment]
@augustosamame Sorry about the late response. I think I need a little more context -- could you post some code?

**Comment by andrewhavens** [comment]
I'm going to close this since it has been open for a long time. Let us know if you need any more help!
