### ISSUE TITLE
How to scroll TableScreen to bottom programatically?

### ISSUE THREAD

**Issue by augustosamame** [infinitered/ProMotion#791]
I implemented a TableScreen as a child screen in a PM::Screen. Now when refreshing the table it does not scroll down automatically like it did when it was a regular PM::TableScreen

Is there any way to fix this or to just implement scrolling down via code to the last cell?
I found this code:

`scrollview.setContentOffset(bottomOffset, animated: true)`

However I am not quite sure how to reference the scrollview in the TableScreen

**Comment by jamonholmgren** [comment]
@augustosamame Sorry about the late reply here. If you haven't figred it out yet, you should be able to access it with `self.tableView`.

**Comment by augustosamame** [comment]
thanks!
