### ISSUE TITLE
Change tab_bar backgroundcolor

### ISSUE THREAD

**Issue by bmoby** [infinitered/ProMotion#792]
Hi im new on rubymotion, this is my 3rd day i started directly with promotion because you did a great job!
Sorry for my bad english im from France...

So my problem is described in the title i would like to customize my tab bar but i have no idea how to find it... so i have i tab_bar like this one:

`open_tab_bar(FirstScreen.new(nav_bar: true), SecondScreen, ...)`

And in my declared screens i have:

`def on init
   set_tab_bar_item title: "first", item: "my-icon"
end`

How can i access the options availible in the UI Documentation? 
Thanks a lot !

**Comment by jamonholmgren** [comment]
Hey @bmoby! Welcome to ProMotion, glad it's been useful.

You'll need to change the `UIAppearance` of all tab bars. Check #341 for an example of how to do that.

**Comment by andrewhavens** [comment]
I'm going to close this issue since it's been open for a long time. Let us know if you need any more help!
