### ISSUE TITLE
Image picker crashes in iOS10

### ISSUE THREAD

**Issue by afestein** [infinitered/ProMotion#795]
Hey guys, got an interesting one. I have a working image picker in my iOS9 app, which is called from a screen with a tab bar:
```
@image_picker = UIImagePickerController.new
@image_picker.delegate = self
@image_picker.sourceType = UIImagePickerControllerSourceTypePhotoLibrary
presentViewController(@image_picker, animated: true, completion: nil)
```

However after upgrading to iOS10 it now crashes:

```
*** Terminating app due to uncaught exception 'NoMethodError', 
reason: 'navigation_controller.rb:14:in 'supportedInterfaceOrientations': 
undefined method 'supportedInterfaceOrientations' for nil:NilClass (NoMethodError)
from tab_bar_controller.rb:115:in `current_view_controller_try:'
from tab_bar_controller.rb:84:in `supportedInterfaceOrientations’
```

If I force `supportedInterfaceOrientations` in `navigation_controller.rb` to return `26` (a valid setting) then it works fine. Seems like `visibleViewController` is actually nil at this point.
I'm still scratching around for a solution but would appreciate any ideas. :smile: :cherries:

**Comment by jamonholmgren** [comment]
Thanks for reporting & fixing @afestein !
