### ISSUE TITLE
'live' and 'pm_live' don't work anymore with version 4.13

### ISSUE THREAD

**Issue by dotvo007** [infinitered/ProMotion#797]
Hi,
'live' and 'pm_live' don't work anymore with version 4.13 in spite of confirmations that it "is now on"

I had had this problem before after upgrading from RubyMotion 4.11 to version 4.12.
The problem had been resolved thanks to an advice in the forum: I should re-install 4.11 and leave a note in the Rakefile $:.unshift('/Library/RubyMotion4.11/lib')
It worked fine after that.

I had hoped that with version 4.13 the problem would be resolved. But it seems that this is not the case. 
This time I cannot switch back to version 4.11 as the version does not support OS-X 10.

Thanks for helping,
Daniel

![bildschirmfoto 2016-09-26 um 09 55 20](https://cloud.githubusercontent.com/assets/7167294/18826828/bc912312-83cf-11e6-8829-b008be3bdb5d.png)

**Comment by jamonholmgren** [comment]
@dotvo007 Do you have any more insight into why it's not working?

**Comment by dotvo007** [comment]
No, unfortunately I don't.

**Comment by jamonholmgren** [comment]
@dotvo007 RubyMotion 4.15 includes a fix that might help with this. Can you confirm?

**Comment by dotvo007** [comment]
Thanks, I have updated to RubyMotion 4.15
Probably I do make some mistake:

When using a simple new "Hello world" app I understand according to the new "Docs >> Live Screen Reloading" instructions that I should just type into the REPL the following: "pm_live_screens". Like before, this should be enough to reload after changes.

According to 
> "However, if your screen does not have any extra setup besides adding views or loading the data source, then you can leave out on_live_reload and allow the base to tear down your views, and re-add for you!"

I don't have to include a "def on_live_reload" or any other piece of code. Right?

Thanks again for helping!
Daniel

**Comment by jamonholmgren** [comment]
> I don't have to include a "def on_live_reload" or any other piece of code. Right?

Correct, that's exactly right. It should just work.

**Comment by dotvo007** [comment]
Thanks for your response!
As I seem to be the only user who has an issue with this feature I conclude that it can only be my Mac's system. I plan to reinstall os x from scratch. This might also resolve the problem I have with 'rake device' which does not work anymore.
Have you any better idea?

**Comment by dotvo007** [comment]
I am still using El Capitan as my Mac is to old to use Sierra. I assume that this cannot be the reason for the problems. Right?

**Comment by jamonholmgren** [comment]
I don't know, unfortunately I no longer use ProMotion on a day to day basis. 😢 We've moved on to React Native and I've switched my focus to Elixir/Elm. You're welcome to continue using PM! I just won't be of much help these days.

**Comment by dotvo007** [comment]
Thanks for your response, Jamon. (And sorry for the delay)
