### ISSUE TITLE
Cynical dependencies

### ISSUE THREAD

**Issue by amirrajan** [infinitered/ProMotion#805]
Probably a good idea to resolve these if possible. RubyMotion's dependency manager now warns if cyclical dependencies are detected. Remove these will allow you to set `app.detect_dependencies = true` in the `Rakefile`.

```
Possible cyclical dependency between
ProMotion/lib/ProMotion/collection/data/collection_data.rb
and
ProMotion/lib/ProMotion/collection/collection.rb's class hierarchy
    
Possible cyclical dependency between
ProMotion/lib/ProMotion/table/data/table_data.rb
and
ProMotion/lib/ProMotion/table/table.rb's class hierarchy
```

**Comment by jamonholmgren** [comment]
`Cynical` dependencies. That's funny, @amirrajan.

This should be possible. Maybe @andrewhavens can look into it.

**Comment by amirrajan** [comment]
... doh

I’m leaving it. :-P

**Comment by andrewhavens** [comment]
I've reviewed the code and I think this issue can be closed.
